"""Generate the optional, synthetic README showcase fixture (Python stdlib only)."""
from datetime import date, timedelta
from pathlib import Path
import json
import math
import random

ROOT = Path(__file__).resolve().parents[2]
rng = random.Random(20260914)
statements = ["-- Optional Lens showcase fixture. Synthetic data only; generated by docs/examples/generate_showcase.py.",
              "-- Import ONCE after schema.sql. Requires datasource 1 to point to this database.",
              "-- Adds independent tables and IDs 97101-97602; does not reset existing data. Do not use mysql --force.",
              "SET NAMES utf8mb4;"]

def sql(value):
    if value is None:
        return 'NULL'
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, (dict, list)):
        value = json.dumps(value, ensure_ascii=False, separators=(',', ':'))
    return "'" + str(value).replace('\\', '\\\\').replace("'", "''") + "'"

def insert(table, columns, rows):
    for offset in range(0, len(rows), 300):
        statements.append(f"INSERT INTO `{table}` ({','.join('`'+c+'`' for c in columns)}) VALUES\n" +
                          ',\n'.join('(' + ','.join(map(sql, r)) + ')' for r in rows[offset:offset+300]) + ';')

def create(table, definition):
    statements.append(f'CREATE TABLE `{table}` ({definition}) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;')

create('lens_demo_growth', 'business_date DATE NOT NULL, region VARCHAR(20) NOT NULL, channel VARCHAR(20) NOT NULL, category VARCHAR(20) NOT NULL, orders INT NOT NULL, revenue DECIMAL(14,2) NOT NULL, profit DECIMAL(14,2) NOT NULL, PRIMARY KEY(business_date,region,channel,category)')
create('lens_demo_acquisition', 'business_date DATE NOT NULL, channel VARCHAR(20) NOT NULL, visits INT NOT NULL, signups INT NOT NULL, activated INT NOT NULL, paid INT NOT NULL, spend DECIMAL(14,2) NOT NULL, revenue DECIMAL(14,2) NOT NULL, PRIMARY KEY(business_date,channel)')
statements.append('START TRANSACTION;')
growth, acquisition = [], []
for day in range(92):
    current = date(2026, 6, 1) + timedelta(days=day)
    trend = 1 + day * .006
    weekly = 1 + .13 * math.sin(day * math.tau / 7)
    for ri, (region, weight) in enumerate([('华东', 1.35), ('华南', 1.12), ('华北', .9), ('西部', .7)]):
        for ci, (channel, factor) in enumerate([('线上商城', 1.4), ('品牌门店', 1), ('合作经销', .65)]):
            for ki, (category, price) in enumerate([('智能数码', 680), ('户外运动', 390), ('家居生活', 260), ('美妆个护', 180), ('精品食品', 95)]):
                orders = round((9 + ki * 2) * weight * factor * trend * weekly * rng.uniform(.82, 1.18))
                revenue = round(orders * price * rng.uniform(.92, 1.08), 2)
                profit = round(revenue * (.27 + ki * .025 + ci * .014), 2)
                growth.append([current, region, channel, category, orders, revenue, profit])
    for ci, (channel, base, rate) in enumerate([('自然搜索', 3200, .064), ('内容社区', 2400, .052), ('付费搜索', 2000, .044), ('社交广告', 1700, .038), ('伙伴推荐', 950, .082)]):
        visits = round(base * trend * weekly * rng.uniform(.92, 1.08))
        signups = round(visits * (.24 + ci*.009))
        activated = round(signups * (.68 + ci*.014))
        paid = round(visits * rate)
        spend = round(visits * [.18,.36,.92,.74,.22][ci], 2)
        revenue = round(paid * [189,209,249,199,299][ci], 2)
        acquisition.append([current, channel, visits, signups, activated, paid, spend, revenue])
insert('lens_demo_growth', ['business_date','region','channel','category','orders','revenue','profit'], growth)
insert('lens_demo_acquisition', ['business_date','channel','visits','signups','activated','paid','spend','revenue'], acquisition)

# The funnel is derived from the same daily rows, so every stage agrees with the KPI cards.
funnel_sql = '\nUNION ALL\n'.join(f"SELECT business_date, channel, '{label}' AS stage, {order} AS stage_order, {field} AS people FROM lens_demo_acquisition" for order, label, field in [(1,'访问网站','visits'),(2,'完成注册','signups'),(3,'激活产品','activated'),(4,'付费转化','paid')])
datasets = [
    (97101, '演示 · 零售增长日表', '模拟零售数据，2026-06 至 2026-08；粒度为日期 × 区域 × 渠道 × 品类。', 'SELECT\n  business_date,\n  region,\n  channel,\n  category,\n  orders,\n  revenue,\n  profit\nFROM lens_demo_growth',
     [('business_date','DATE','业务日期'),('region','STRING','区域'),('channel','STRING','销售渠道'),('category','STRING','商品品类'),('orders','NUMBER','订单数'),('revenue','NUMBER','营收（元）'),('profit','NUMBER','毛利（元）')]),
    (97102, '演示 · 渠道获客日表', '模拟获客数据，按日期和渠道汇总访问、注册、激活、付费、投放与收入。', 'SELECT * FROM lens_demo_acquisition',
     [('business_date','DATE','业务日期'),('channel','STRING','获客渠道'),('visits','NUMBER','访问人数'),('signups','NUMBER','注册人数'),('activated','NUMBER','激活人数'),('paid','NUMBER','付费人数'),('spend','NUMBER','投放费用（元）'),('revenue','NUMBER','付费收入（元）')]),
    (97103, '演示 · 获客转化漏斗', '由渠道获客日表展开的顺序漏斗，各阶段人数为嵌套子集，与获客指标保持一致。', funnel_sql,
     [('business_date','DATE','业务日期'),('channel','STRING','获客渠道'),('stage','STRING','转化阶段'),('stage_order','NUMBER','阶段顺序'),('people','NUMBER','阶段人数')]),
]
# Translate dimensions at query time; the English showcase uses the same underlying facts.
english_dimensions = {
    'region': [('华东', 'East'), ('华南', 'South'), ('华北', 'North'), ('西部', 'West')],
    'channel': [('线上商城', 'Online'), ('品牌门店', 'Stores'), ('合作经销', 'Partners')],
    'category': [('智能数码', 'Electronics'), ('户外运动', 'Outdoor'), ('家居生活', 'Home'), ('美妆个护', 'Beauty'), ('精品食品', 'Grocery')],
}
english_sql = 'SELECT\n  business_date,\n' + ',\n'.join(
    '  CASE ' + field + ' ' + ' '.join(f'WHEN {sql(source)} THEN {sql(label)}' for source, label in mapping)
    + f' ELSE {field} END AS {field}' for field, mapping in english_dimensions.items()
) + ',\n  orders,\n  revenue,\n  profit\nFROM lens_demo_growth'
datasets.append((97104, 'Demo · Retail growth (English)',
                 'Synthetic daily retail facts, Jun–Aug 2026. English dimensions; monetary values remain in CNY.', english_sql,
                 [('business_date','DATE','Business date'),('region','STRING','Region'),('channel','STRING','Sales channel'),
                  ('category','STRING','Product category'),('orders','NUMBER','Orders'),('revenue','NUMBER','Revenue'),('profit','NUMBER','Gross profit (CNY)')]))
for ident, name, desc, query, fields in datasets:
    insert('vis_dataset', ['id','source_id','dataset_name','dataset_desc','sql_content','param_demo','status','create_by'], [[ident,1,name,desc,query,'{}','EBL',1]])
    insert('vis_dataset_field', ['id','dataset_id','field','data_type','suggest_role','remark','sort_num','status'],
           [[ident*100+i,ident,f,t,'METRIC' if t=='NUMBER' and f!='stage_order' else 'DIMENSION',label,i,'EBL'] for i,(f,t,label) in enumerate(fields,1)])

cards = []
def metric(field, label, formula=None):
    return dict(field=field, label=label, **({'formula':formula} if formula else {'agg':'SUM'}))
def dim(field,label,grain=None):
    return dict(field=field,label=label,**({'timeGrain':grain} if grain else {}))
def card(ident,name,kind,dataset,metrics,dimensions=None,chart=None,order=None,visual=None,month=True):
    query = dict(datasetId=str(dataset),asOfDate='2026-08-31',metrics=metrics,dimensions=dimensions or [],orderList=order or [])
    if month:
        query['filters']=[dict(combineOp='and',conditions=[dict(field='business_date',valueExp='current_month')])]
    config = dict(chartType=kind,showTitle=True,allowDetail=True,allowDownload=True,detail=dict(fields=[f[0] for d in datasets if d[0]==dataset for f in d[4]]))
    if chart:
        config['chart']=chart
    if visual:
        config.update(visual)
    cards.append(dict(id=ident,cardName=name,cardDesc='模拟数据 · 2026年8月' if month else '模拟数据 · 2026年6–8月',datasetId=dataset,chartType=kind,queryJson=query,visualJson=config,status='EBL'))
    return ident

def fmt(field,suffix='',decimals=1,compact=False,prefix=''):
    key=f'm:{field}:SUM'
    return dict(key=key,sourceUid=key,kind='metric',format=dict(decimals=decimals,compact=compact,suffix=suffix,prefix=prefix))
def numeric(field, suffix='', color='#2563eb', decimals=1, compact=False, prefix=''):
    return dict(number=dict(showLabel=False,showAuxLabel=False,color=color),fieldStyles=[fmt(field,suffix,decimals,compact,prefix)])
rev=metric('revenue','营收'); profit=metric('profit','毛利'); orders=metric('orders','订单数')
card(97201,'8月总营收','number',97101,[rev],visual=numeric('revenue',compact=True,prefix='¥'))
card(97202,'成交订单','number',97101,[orders],visual=numeric('orders',suffix=' 单',decimals=0,color='#0d9488'))
card(97203,'综合毛利率','number',97101,[metric('margin','毛利率','SUM(profit)/SUM(revenue)*100')],visual=numeric('margin','%',color='#7c3aed'))
card(97204,'平均客单价','number',97101,[metric('aov','客单价','SUM(revenue)/SUM(orders)')],visual=numeric('aov',prefix='¥',color='#d97706'))
card(97205,'8月营收趋势 · 日度','line',97101,[rev,profit],[dim('business_date','日期','day')],chart=dict(area=True,smooth=True,legendPosition='top'),order=[dict(field='日期',dir='asc')])
card(97206,'销售渠道贡献','pie',97101,[rev],[dim('channel','渠道')],chart=dict(donut=True,legendPosition='bottom',dataLabel=False))
card(97207,'品类营收对比','bar',97101,[rev],[dim('category','品类')],chart=dict(orientation='horizontal',legend=False),order=[dict(field='营收',dir='desc')])
card(97208,'区域业绩排行','rank',97101,[rev],[dim('region','区域')],order=[dict(field='营收',dir='desc')],visual=dict(rank=dict(showPercent=True),fieldStyles=[fmt('revenue',compact=True)]))
card(97209,'品类营收版图','treemap',97101,[rev],[dim('category','品类')],chart=dict(dataLabel=True))
card(97210,'区域经营明细','table',97101,[rev,profit,orders,metric('margin','毛利率','SUM(profit)/SUM(revenue)*100')],[dim('region','区域'),dim('category','品类')],order=[dict(field='营收',dir='desc')],visual=dict(table=dict(striped=True,showRowNumber=True),fieldStyles=[fmt('revenue',decimals=0),fmt('profit',decimals=0),fmt('margin','%')]))
card(97211,'8月访问人数','number',97102,[metric('visits','访问人数')],visual=numeric('visits',compact=True))
card(97212,'新增付费用户','number',97102,[metric('paid','付费人数')],visual=numeric('paid',decimals=0,color='#0d9488'))
card(97213,'访问付费转化率','number',97102,[metric('conversion','转化率','SUM(paid)/SUM(visits)*100')],visual=numeric('conversion','%',color='#7c3aed',decimals=2))
card(97214,'付费获客成本','number',97102,[metric('cac','获客成本','SUM(spend)/SUM(paid)')],visual=numeric('cac',prefix='¥',color='#d97706'))
card(97215,'访问 → 注册 → 激活 → 付费','funnel',97103,[metric('people','人数')],[dim('stage','阶段')],chart=dict(showRate=True),order=[dict(field='人数',dir='desc')])
card(97216,'每日新增付费 · 渠道趋势','line',97102,[metric('paid','付费人数')],[dim('business_date','日期','day'),dim('channel','渠道')],chart=dict(smooth=True,legendPosition='top'),order=[dict(field='日期',dir='asc')])
card(97217,'渠道付费贡献','pie',97102,[metric('paid','付费人数')],[dim('channel','渠道')],chart=dict(donut=True,legendPosition='bottom',dataLabel=False))
card(97218,'渠道获客成本对比','bar',97102,[metric('cac','获客成本','SUM(spend)/SUM(paid)')],[dim('channel','渠道')],chart=dict(orientation='horizontal',legend=False),order=[dict(field='获客成本',dir='asc')])
card(97219,'渠道转化明细','table',97102,[metric('visits','访问人数'),metric('paid','付费人数'),metric('conversion','转化率','SUM(paid)/SUM(visits)*100')],[dim('channel','渠道')],visual=dict(table=dict(striped=True),fieldStyles=[fmt('conversion','%',decimals=2)]),order=[dict(field='付费人数',dir='desc')])
revenue_m = metric('revenue_m', 'Revenue', 'SUM(revenue)/1000000')
revenue_k = metric('revenue_k', 'Revenue', 'SUM(revenue)/1000')
profit_k = metric('profit_k', 'Gross profit', 'SUM(profit)/1000')
card(97301,'August revenue','number',97104,[revenue_m],visual=numeric('revenue_m','M',color=None,decimals=2,prefix='CNY '))
card(97302,'Orders placed','number',97104,[metric('orders','Orders')],visual=numeric('orders',color=None,decimals=0))
card(97303,'Gross margin','number',97104,[metric('margin','Gross margin','SUM(profit)/SUM(revenue)*100')],visual=numeric('margin','%',color=None))
card(97304,'Average order value','number',97104,[metric('aov','Average order value','SUM(revenue)/SUM(orders)')],visual=numeric('aov',color=None,decimals=2,prefix='CNY '))
card(97305,'Daily revenue & profit · CNY k','line',97104,[revenue_k,profit_k],[dim('business_date','Date','day')],chart=dict(area=True,smooth=True,legendPosition='top'),order=[dict(field='Date',dir='asc')])
card(97306,'Revenue by channel','pie',97104,[metric('revenue','Revenue')],[dim('channel','Channel')],chart=dict(donut=True,centerText=False,legendPosition='bottom',dataLabel=False))
card(97307,'Revenue by category · CNY k','bar',97104,[revenue_k],[dim('category','Category')],chart=dict(orientation='horizontal',legend=False),order=[dict(field='Revenue',dir='desc')])
card(97308,'Regional leaderboard · CNY M','rank',97104,[revenue_m],[dim('region','Region')],order=[dict(field='Revenue',dir='desc')],visual=dict(rank=dict(showPercent=True),fieldStyles=[fmt('revenue_m','M',decimals=2)]))
card(97309,'Category revenue mix','treemap',97104,[metric('revenue','Revenue')],[dim('category','Category')],chart=dict(dataLabel=True))
for c in cards:
    if c['datasetId'] == 97104:
        c['cardDesc'] = 'Synthetic data · August 2026 · CNY'
for c in cards:
    insert('vis_card',['id','card_name','card_desc','dataset_id','chart_type','query_json','visual_json','status','create_by'],[[c[k] for k in ['id','cardName','cardDesc','datasetId','chartType','queryJson','visualJson','status']]+[1]])
insert('vis_dash_group',['id','pid','group_name','icon','sort_num','status'],[[97601,0,'产品演示','chart-line-line',0,'EBL']])
def widget(ident,x,y,w,h):
    return dict(kind='card',cardId=str(ident),x=x,y=y,w=w,h=h)
growth_layout=[widget(97201+i,i*6,0,6,4) for i in range(4)]+[widget(97205,0,4,16,8),widget(97206,16,4,8,8),widget(97207,0,12,8,7),widget(97208,8,12,8,7),widget(97209,16,12,8,7)]
acq_layout=[widget(97211+i,i*6,0,6,4) for i in range(4)]+[widget(97215,0,4,9,8),widget(97216,9,4,15,8),widget(97217,0,12,7,7),widget(97218,7,12,8,7),widget(97219,15,12,9,7)]
english_layout=[dict(item,cardId=str(int(item['cardId'])+100)) for item in growth_layout]
dashboards = [
    (97501,'零售增长驾驶舱','DEMO / 2026.08 · 营收、渠道与商品结构 · 模拟数据',97101,growth_layout,'t1'),
    (97502,'渠道增长与转化','DEMO / 2026.08 · 从流量到付费，追踪增长效率 · 模拟数据',97102,acq_layout,'t4'),
    (97503,'Retail Growth Overview','AUG 2026 / SYNTHETIC DATA · Revenue, channels & product mix · CNY',97104,english_layout,'t1'),
    (97504,'Retail Growth · Dark','AUG 2026 / SYNTHETIC DATA · Revenue, channels & product mix · CNY',97104,english_layout,'t6'),
]
for ident,name,desc,dataset,layout,theme in dashboards:
    config=dict(theme=theme,cardRadius='lg',widgets=layout,filters=[])
    insert('vis_dashboard',['id','group_id','dash_name','dash_desc','config_json','status','create_by'],[[ident,97601,name,desc,config,'EBL',1]])
    insert('vis_dashboard_card',['id','dashboard_id','card_id'],[[ident*100+i,ident,int(w['cardId'])] for i,w in enumerate(layout,1)])
    insert('sys_role_dashboard',['id','role_id','dashboard_id','create_by'],[[ident,1,ident,1]])
statements.append('COMMIT;')
output=ROOT/'backend/db/showcase.sql'
output.write_text('\n\n'.join(statements)+'\n')
print(f'{output}: {len(growth)} retail rows, {len(acquisition)} acquisition rows, {len(datasets)} datasets, {len(cards)} cards, {len(dashboards)} dashboards')
