/** 查看、保存和订阅入口共用的视图文案。 */
export const DASHBOARD_VIEW_COPY = {
  title: '视图',
  defaultName: '看板默认',
  defaultDescription: '使用看板预设的筛选条件和标签页。',
  currentName: '当前视图',
  savedGroup: '我的视图',
  empty: '尚未保存视图',
  modified: '已修改',
  unsaved: '未保存',
  save: '保存视图',
  saveChanges: '保存更改',
  saveAs: '另存新视图',
  restore: '放弃更改',
  restoreDescription: '恢复此视图上次保存的筛选条件和标签页。',
  reset: '恢复看板默认',
  manage: '管理视图',
  defaultBadge: '默认打开',
  setDefault: '设为默认打开',
  setDefaultDescription: '设为默认打开，下次进入此看板时自动使用。',
  clearDefault: '取消默认打开',
  clearDefaultDescription: '取消默认打开，下次使用看板默认设置。',
  saveDescription: '保存当前筛选条件和标签页选择，方便下次查看。',
  share: '复制链接',
  linkCopied: '链接已复制',
  subscriptionSaved: '订阅保存的视图',
} as const
