server:
  port: 8080
  compression:
    enabled: true
    min-response-size: 2KB

spring:
  application:
    name: lens
  web:
    resources:
      chain:
        enabled: true
        compressed: true
      static-locations:
        - classpath:/META-INF/resources/
        - classpath:/resources/
        - classpath:/static/
        - classpath:/public/
        - file:./ui/
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/lens?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: Aa123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: Aa123456
      timeout: 3s

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    banner: false

lens:
  jwt-secret: lens-dev-token-secret-change-me
  jwt-ttl-ms: 43200000

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method
